version: "3.7"

services:
  mongole:
    image: mongo:4.0.1
    restart: always
    container_name: mongole
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro


  mongolexpress:
    image: mongo-express
    container_name: mongolexpress
    restart: always  #restart the container regardless of the exit status
    depends_on:
      - mongole
    ports:
      - 8086:8081  # port forwarding
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongole:27017/  # mongodb://{mongo-image-username}:{mongo-image-password}@{mongo-image-name}:{port}

  numexcellent:
    #    build: .
    image: 672727997648.dkr.ecr.eu-central-1.amazonaws.com/lotto:latest
    restart: always
    ports:
      - 8001:8088
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: admin
      MONGO_HOST: mongole
      MONGO_PORT: 27017

#networks:
#  default:
#    external:
#      name: my-network